COMMAND_FORMATS = {
    0: "Reserved",
    1: "Lighting",
    2: "Moving Lights",
    3: "Colour Changers",
    4: "Strobes",
    5: "Lasers",
    6: "Chasers",
    16: "Sound",
    17: "Music",
    18: "CD Players",
    19: "EEPROM Playback",
    20: "Audio Tape Machines",
    21: "Intercoms",
    22: "Amplifiers",
    23: "Audio Effects Devices",
    24: "Equalisers",
    32: "Machinery",
    33: "Rigging",
    34: "Flys",
    35: "Lifts",
    36: "Turntables",
    37: "Trusses",
    38: "Robots",
    39: "Animation",
    40: "Floats",
    41: "Breakaways",
    42: "Barges",
    48: "Video",
    49: "Video Tape Machines",
    50: "Video Cassette Machines",
    51: "Video Disc Players",
    52: "Video Switchers",
    53: "Video Effects:",
    54: "Video Character Generators",
    55: "Video Still Stores",
    56: "Video Monitors",
    64: "Projection",
    65: "Film Projectors",
    66: "Slide Projectors",
    67: "Video Projectors",
    68: "Dissolvers",
    69: "Shutter Controls",
    80: "Process Control",
    81: "Hydraulic Oil",
    82: "H2O",
    83: "CO2",
    84: "Compressed Air",
    85: "Natural Gas",
    86: "Fog",
    87: "Smoke",
    88: "Cracked Haze",
    96: "Pyro",
    97: "Fireworks",
    98: "Explosions",
    99: "Flame",
    100: "Smoke Pots",
    127: "All-Types"
}

COMMAND_TYPES = {
    0: "Reserved",
    1: "GO",
    2: "STOP",
    3: "RESUME",
    4: "TIMED_GO",
    5: "LOAD",
    6: "SET",
    7: "FIRE",
    8: "ALL_OFF",
    9: "RESTORE",
    10: "RESET",
    11: "GO_OFF",
    16: "GO/JAM CLOCK",
    17: "STANDBY_+",
    18: "STANDBY_-",
    19: "SEQUENCE_+",
    20: "SEQUENCE_-",
    21: "START_CLOCK",
    22: "STOP_CLOCK",
    23: "ZERO_CLOCK",
    24: "SET_CLOCK",
    25: "MTC_CHASE_ON",
    26: "MTC_CHASE_OFF",
    27: "OPEN_CUE_LIST",
    28: "CLOSE_CUE_LIST",
    29: "OPEN_CUE_PATH",
    30: "CLOSE_CUE_PATH"
}
